# Form implementation generated from reading ui file '.\app\ui_form\ui\cookies.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CookiesWindow(object):
    def setupUi(self, CookiesWindow):
        CookiesWindow.setObjectName("CookiesWindow")
        CookiesWindow.resize(442, 468)
        self.centralwidget = QtWidgets.QWidget(parent=CookiesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(150, 40))
        self.closeButton.setStyleSheet("    QPushButton {\n"
"        background-color: #f44336; /* Красный цвет */\n"
"        border: none;\n"
"        color: white;\n"
"        text-align: center;\n"
"        text-decoration: none;\n"
"        font-size: 16px;\n"
"        margin: 4px 2px;\n"
"        border-radius: 10px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: #d32f2f; /* Цвет при наведении на кнопку */\n"
"    }\n"
"\n"
"    QPushButton:pressed {\n"
"        background-color: #b71c1c; /* Цвет при нажатии на кнопку */\n"
"    }")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setMinimumSize(QtCore.QSize(150, 40))
        self.saveButton.setStyleSheet("    QPushButton {\n"
"        background-color: #4CAF50; /* Зеленый цвет */\n"
"        border: none;\n"
"        color: white;\n"
"        text-align: center;\n"
"        text-decoration: none;\n"
"        font-size: 16px;\n"
"        margin: 4px 2px;\n"
"        border-radius: 10px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: #45a049; /* Цвет при наведении на кнопку */\n"
"    }\n"
"\n"
"    QPushButton:pressed {\n"
"        background-color: #3e8e41; /* Цвет при нажатии на кнопку */\n"
"    }")
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        CookiesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CookiesWindow)
        QtCore.QMetaObject.connectSlotsByName(CookiesWindow)

    def retranslateUi(self, CookiesWindow):
        _translate = QtCore.QCoreApplication.translate
        CookiesWindow.setWindowTitle(_translate("CookiesWindow", "MainWindow"))
        self.closeButton.setText(_translate("CookiesWindow", "Отмена"))
        self.saveButton.setText(_translate("CookiesWindow", "Сохранить"))
